from decouple import config

DATCAT_SCHEME = config("DATCAT_SCHEME")
DATCAT_HOST = config("DATCAT_HOST")
DATCAT_PORT = config("DATCAT_PORT")
DATCAT_DEBUG = config("DATCAT_DEBUG")

CATASYN_SCHEME = config("CATASYN_SCHEME")
CATASYN_HOST = config("CATASYN_HOST")
CATASYN_PORT = config("CATASYN_PORT")
CATASYN_DEBUG = config("CATASYN_DEBUG")

SCHEDULE_INTERVAL_SECONDS = config("SCHEDULE_INTERVAL_SECONDS", cast=int)
SCHEDULE_SLEEP_SECONDS = config("SCHEDULE_SLEEP_SECONDS", cast=int)
SCHEDULER_LOG_ROOT = config("SCHEDULER_LOG_ROOT")

CLOUD_PROJECT_ID = config("CLOUD_PROJECT_ID")
DATASET = config("DATASET")
LOCATION = config("LOCATION")
GOOGLE_APPLICATION_CREDENTIALS = config("GOOGLE_APPLICATION_CREDENTIALS")
